version: '3'
services:

  ever-to-md:
    image: "daocloud.io/shutdown/ever-go-md:v0.1.1"
    environment:
      - GOOS=windows
    volumes:
      - "${FROM}:/from"
      - tmp:/to

  md-to-web:
    image: "daocloud.io/shutdown/my-minina:v0.1.1"
    depends_on: ["ever-to-md"]
    volumes:
      - tmp:/from
      - "${TO}:/to"

volumes:
  tmp:
